---
title: "scraping and cleaning strava data"
format: html
editor: visual
---

```{r}
#load necessary packages -------
library(rStrava)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(lubridate)
library(googleway)
library(htmlwidgets)
library(leaflet)
library(htmltools)

```

```{r}

my_token <- httr::config(token = strava_oauth(app_name, app_client_id, app_secret, app_scope = "activity:read_all", cache = TRUE))

#..................create strava token (cached)..................
my_token <- httr::config(token = readRDS('.httr-oauth')[[1]])
```

```{r}
#scrape strava activities-----------
my_actvities <- rStrava::get_activity_list(stoken = my_token)

```

```{r}
activity_df <- rStrava::compile_activities(my_actvities)
```

### Wrangle Data

##### Convert km into miles and time into minutes, round all other numeric variables

```{r}
cleaned_activities <- rStrava::compile_activities(my_actvities) %>% 
  mutate(distance_miles = round(distance * 0.62137, digits =2),
         elevation_gain_ft = round(total_elevation_gain* 3.28084, digits = 2),
         average_speed_miles = round(average_speed *0.62137, digits = 2),
         elasped_time_min = round(elapsed_time/60, digits = 2),
         elev_high_ft = round(elev_high* 3.28084, digits = 2),
         elev_low_ft = round(elev_low* 3.28084, digits = 2),
         max_speed_miles = round(max_speed *0.62137, digits = 2),
         moving_time_min = round(moving_time/60, digits = 2),
         average_temp_f = round((as.numeric(average_temp)* (9/5)) +32, digits = 2),
         start_date = as_datetime(start_date),
         ) %>% 
  select(
    achievement_count, athlete_count,distance_miles,elevation_gain_ft,
    average_speed_miles,elasped_time_min, elev_high_ft, elev_low_ft,
    max_speed_miles, moving_time_min, average_temp_f, start_date, 
    end_latlng1, end_latlng2,external_id, id, kudos_count, map.id, map.resource_state, map.summary_polyline, name, pr_count, resource_state, sport_type, start_latlng1, start_latlng2, timezone, type, upload_id, upload_id_str, utc_offset)
  
```

```{r}
# Initialize an empty list to store data frames
decoded_paths <- list()

for (i in seq_along(map_activities$map.summary_polyline)) {
  polyline <- map_activities$map.summary_polyline[i]
  if (!is.na(polyline) && nchar(polyline) > 0) {
    decoded_path <- decode(polyline)
    # Convert list to data frame if necessary
    if (is.list(decoded_path)) {
      decoded_df <- do.call(rbind, lapply(decoded_path, as.data.frame))
      decoded_df$activity_id <- i  # Add an identifier for the activity
      decoded_paths[[i]] <- decoded_df
    } else {
      message("Skipping activity ", i, ": decoded path is not a list.")
    }
  }
}

# Combine all data frames into one
all_decoded_paths <- do.call(rbind, decoded_paths)



```

```{r}
library(ggplot2)

# Creating the plot with invisible facet labels
strava_map <- ggplot(data = all_decoded_paths, aes(x = lon, y = lat)) +
  geom_path(color = "black", size = 1) +  # Draw the paths
  facet_wrap(~ activity_id, scales = "free", strip.position = "bottom") +  # Organize by activity_id without labels
  theme_void() +  # Apply a theme with no background or axes
  theme(strip.text = element_blank(),
        plot.background = element_rect(fill = "white", colour = "white"),  
  panel.background = element_rect(fill = "white", colour = "white")) 
ggsave("strava_map.png", plot = last_plot())


```
